# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e91217eccafa56b68e4c495b624f0e2fdb6f63f3134fe58c703a5912866c937e68b859c307be7019b953064d31ed2f7da4ea9a95beb0bc4721cc10fb5e501cff

test:
  secret_key_base: 1f77791e2c60442fd2adf16f9b7a8a73302a99c13f659d635a0d16774d842085805ee386191d49af2f132ff7e78d6302d1499455262f9e94458eb9be6bd98115

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
